### PR TITLE
Dont raise error if len(_names) < self.field_count()

### PR DESCRIPTION
**Pull request by PanosFirmpas**
Hi,

I run into this error all the time when converting to dataframe.
Since pandas is more than happy to deal with names=None, I find raising an error here quite unnecessary.

I changed the error to a warning, and let it pass _names=None when the default names don't fit.

### CODE REVIEW

**Comment by daler** [comment]
This sounds good. There's a test that's failing because it's expecting a ValueError, would you fix that as well so the test suite passes?

**Comment by PanosFirmpas** [comment]
I think I got it :D

**Comment by daler** [comment]
Thanks!

**Comment by PanosFirmpas** [comment]
Cool!

Thanks a lot for the repo, it's a life saver !

**Comment by kyleabeauchamp** [comment]
Any thoughts on the release schedule?  Looks like there have been 16 commits (including fixes) since last release.

**Comment by daler** [comment]
Thanks for the reminder. I just pushed v0.7.8 to PyPI but apparently they're doing maintenance at the moment and the URL to the tarball doesn't seem to match previous patterns. So I'll wait for tomorrow before updating the bioconda package.

**Pull request merged**
