### PR TITLE
further set_path fixes

### PR DESCRIPTION
**Pull request by daler**
xref #218, #220, #221, #222 

Thanks @lonsbio for pointing out that `example_bedtool` worked but `BedTool` didn't -- until then I was stumped as to why the tests were working but issues were still being reported.

The solution here was to reload both `pybedtools.bedtool` as well as `pybedtools` as a whole. The latter is to ensure the `bedtool` module imported into `pybedtools.__init__` is reloaded as well. I thought that should have happened anyway, but I guess I hadn't fully understood how the reloading works (it's not recursive).

I also improved the test to check both `example_bedtool`-created and `pybedtools.BedTool` objects.

I haven't quite worked out how to reload when someone uses `from pybedtools import BedTool`. I suspect a deep reload (like IPython's deepreload) will be needed here. https://github.com/ipython/ipython/blob/master/IPython/lib/deepreload.py is BSD licensed at least.

@lonsbio, @jordeu, @croth1 would you mind giving this a spin? Sorry all that it's taken a while -- it's been a busy couple of weeks.

### CODE REVIEW

**Comment by lonsbio** [comment]
Works with my use case! Thanks!

**Comment by gouthamatla** [comment]
Hi All, Is this fixed ? I am having the issues with pybedtools to find bedtools in jupyter notebook. May I know how to fix it ?

**Comment by daler** [comment]
@gouthamatla what is the error you're getting?

In a jupyter notebook, are you able to call bedtools via the shell (e.g., `! bedtools`)? If not, you'll need to make sure bedtools is on your `$PATH`.

**Comment by gouthamatla** [comment]
Thanks. Seems like my Jupyter is unable to find shell commands. I will try to fix that. In any case, set_bedtools_path() is not effective.

**Pull request merged**
