### PR TITLE
Testing a fix for an issue with pathlib

### PR DESCRIPTION
**Pull request by dbolser**
Seems working in my preliminary tests... Lest see if the PR fires off your CI pipelines ;-)

### CODE REVIEW

**Comment by dbolser** [comment]
Reference issue https://github.com/daler/pybedtools/issues/405

**Comment by dbolser** [comment]
Sorry, I didn't test properly! This doesn't work with a file string... I just assumed os.PathLike would work with that :(

**Comment by dbolser** [comment]
I've searched around and I'm not sure how to fix this.

**Comment by daler** [comment]
addressed in #404 (specifically https://github.com/daler/pybedtools/commit/7b3bb92cea93cb55a206db5d076d3a613bb852c1), thanks for reporting.

**Pull request closed without merging**
